apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Welcome to My Apache Server</title>
    </head>
    <body>
        <h1>Welcome to My Apache Web Server!</h1>
        <p>This is a simple index.html page served by Apache.</p>
    </body>
    </html>